### ISSUE TITLE
New players appear in top 3

### ISSUE THREAD

**Issue by dentych** [MartinCarpentier/bizbattle#13]
WHY?!

I blame EloOrder. What even is this? @MartinCarpentier

**Comment by MartinCarpentier** [comment]
I added EloOrder, because you can't ask firebase to sort your array for you. I checked, and read, that you need to add a variable to sort on (EloOrder).

**Comment by MartinCarpentier** [comment]
What i mean, is that you can't specify sort ascending or descending. It's always ascending from firebase. 

Maybe a better solution is to pull the database out into a new webservice, and use a different solution than firebase.
